name: QuestPointers
authors:
  - Md5Lukas
main: de.md5lukas.questpointers.QuestPointers
loader: de.md5lukas.questpointers.DependencyYmlLoader
version: ${version}

website: https://github.com/Sytm/quest-pointers

api-version: "1.20"

permissions:
  questpointers.command:
    default: op
