name: QuestPointers
authors:
  - Md5Lukas
main: de.md5lukas.questpointers.QuestPointers
version: ${version}

website: https://github.com/Sytm/quest-pointers

api-version: "1.20"
folia-supported: true

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}

permissions:
  questpointers.command:
    default: op
